//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Operaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Operaciones()
        {
            this.TBL_Perfil_Operacion = new HashSet<TBL_Perfil_Operacion>();
        }
    
        public int Id_Operacion { get; set; }
        public string Nombre_Operacion { get; set; }
        public Nullable<int> Id_Modulo { get; set; }
    
        public virtual TBL_Modulos TBL_Modulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Perfil_Operacion> TBL_Perfil_Operacion { get; set; }
    }
}
