//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RprtCuentasxCobrar
    {
        public int Id_RprtCtasxCobrar { get; set; }
        public System.DateTime Fecha_reporte { get; set; }
        public decimal Total_Ventas_Credito { get; set; }
        public decimal Total_Pagado { get; set; }
        public decimal Total_Intereses_Mora { get; set; }
        public decimal Total_factura { get; set; }
        public Nullable<int> Id_CuentaCobrar { get; set; }
    
        public virtual TBL_CuentasCobrar TBL_CuentasCobrar { get; set; }
    }
}
