//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DescuentosEstandar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DescuentosEstandar()
        {
            this.TBL_Factura = new HashSet<TBL_Factura>();
        }
    
        public int Id_DescEstandar { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public Nullable<System.DateTime> Fecha_modificacion { get; set; }
        public int Cantidad_Minima { get; set; }
        public int Cantidad_Maxima { get; set; }
        public int Descuento { get; set; }
        public string Dia { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Factura> TBL_Factura { get; set; }
    }
}
