//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Detalle_Orden_Fabricacion
    {
        public int Id_Detalle { get; set; }
        public string Desc_Producto { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> Id_Orden { get; set; }
        public Nullable<int> Id_producto { get; set; }
    
        public virtual TBL_Orden_Fabricacion TBL_Orden_Fabricacion { get; set; }
        public virtual TBL_Productos TBL_Productos { get; set; }
    }
}
