//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Reciclaje
    {
        public int Id_Reciclaje { get; set; }
        public System.DateTime Fecha_reciclado { get; set; }
        public string Descripcion_producto { get; set; }
        public int Cantidad_unidades { get; set; }
        public Nullable<int> Id_Tipo_Reciclaje { get; set; }
        public Nullable<int> Id_producto { get; set; }
    
        public virtual TBL_Productos TBL_Productos { get; set; }
        public virtual TBL_Tipo_Reciclaje TBL_Tipo_Reciclaje { get; set; }
    }
}
