//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Cantones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Cantones()
        {
            this.TBL_Direcciones_cliente = new HashSet<TBL_Direcciones_cliente>();
            this.TBL_Distritos = new HashSet<TBL_Distritos>();
        }
    
        public string Id_canton { get; set; }
        public string Desc_canton { get; set; }
        public string Id_provincia { get; set; }
    
        public virtual TBL_Provincias TBL_Provincias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Direcciones_cliente> TBL_Direcciones_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Distritos> TBL_Distritos { get; set; }
    }
}
