//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Cuentas_por_pagar
    {
        public int Id_CxP { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_modulo { get; set; }
        public System.DateTime Fecha_factura { get; set; }
        public string Tipo_devolucion { get; set; }
        public decimal Monto_devolucion { get; set; }
        public Nullable<int> Id_factura { get; set; }
    
        public virtual TBL_Factura TBL_Factura { get; set; }
    }
}
