//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Factura()
        {
            this.TBL_CierreCajas = new HashSet<TBL_CierreCajas>();
            this.TBL_Cuentas_por_pagar = new HashSet<TBL_Cuentas_por_pagar>();
            this.TBL_CuentasCobrar = new HashSet<TBL_CuentasCobrar>();
            this.TBL_Detalle_Factura = new HashSet<TBL_Detalle_Factura>();
            this.TBL_Orden_Fabricacion = new HashSet<TBL_Orden_Fabricacion>();
            this.TBL_RprtCierreCajas = new HashSet<TBL_RprtCierreCajas>();
            this.TBL_Devoluciones = new HashSet<TBL_Devoluciones>();
        }
    
        public int Id_factura { get; set; }
        public string Tipo_Factura { get; set; }
        public string Tipo_Pago { get; set; }
        public decimal Subtotal { get; set; }
        public decimal SubtotalDescuento { get; set; }
        public decimal Total_impuesto { get; set; }
        public decimal Total { get; set; }
        public System.DateTime Fecha_venta { get; set; }
        public Nullable<int> Id_estado { get; set; }
        public Nullable<int> Id_cliente { get; set; }
        public Nullable<int> Id_DescVIP { get; set; }
        public Nullable<int> Id_DescEstandar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CierreCajas> TBL_CierreCajas { get; set; }
        public virtual TBL_Clientes TBL_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Cuentas_por_pagar> TBL_Cuentas_por_pagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CuentasCobrar> TBL_CuentasCobrar { get; set; }
        public virtual TBL_DescuentosEstandar TBL_DescuentosEstandar { get; set; }
        public virtual TBL_DescuentosVIP TBL_DescuentosVIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Detalle_Factura> TBL_Detalle_Factura { get; set; }
        public virtual TBL_Estado TBL_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Orden_Fabricacion> TBL_Orden_Fabricacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RprtCierreCajas> TBL_RprtCierreCajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Devoluciones> TBL_Devoluciones { get; set; }
    }
}
