//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Direcciones_cliente
    {
        public int Id_direccion { get; set; }
        public string Dsc_direccion { get; set; }
        public string Id_provincia { get; set; }
        public string Id_canton { get; set; }
        public string Id_distrito { get; set; }
        public int Id_cliente { get; set; }
    
        public virtual TBL_Cantones TBL_Cantones { get; set; }
        public virtual TBL_Clientes TBL_Clientes { get; set; }
        public virtual TBL_Distritos TBL_Distritos { get; set; }
        public virtual TBL_Provincias TBL_Provincias { get; set; }
    }
}
