//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BeerLab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BeerLab()
        {
            this.TBL_Usuarios = new HashSet<TBL_Usuarios>();
        }
    
        public int Id_Empresa { get; set; }
        public string Cedula_Juridica { get; set; }
        public string Nombre { get; set; }
        public int Telefono { get; set; }
        public string Direccion_fisica { get; set; }
        public string Correo_electronico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Usuarios> TBL_Usuarios { get; set; }
    }
}
