//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Ubicaciones
    {
        public string Id_Ubicacion { get; set; }
        public string Num_Almacen { get; set; }
        public int Num_Pasillo { get; set; }
        public int Num_Estante { get; set; }
        public string Tipo_Envasado { get; set; }
        public string Tipo_Cerveza { get; set; }
        public string Nivel_Fragilidad { get; set; }
        public string Ubicacion_Estante { get; set; }
        public string Ubicacion_receptora { get; set; }
        public string Ubicacion_entrega { get; set; }
        public decimal Peso_Lote { get; set; }
        public int Cantidad_Lote { get; set; }
        public System.DateTime Fecha_Produccion { get; set; }
        public decimal Valor_Lote { get; set; }
        public int Id_producto { get; set; }
    
        public virtual TBL_Productos TBL_Productos { get; set; }
    }
}
