//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Perfil_Operacion
    {
        public int Id_PerfilO { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public Nullable<int> Id_Operacion { get; set; }
    
        public virtual TBL_Operaciones TBL_Operaciones { get; set; }
        public virtual TBL_Roles TBL_Roles { get; set; }
    }
}
