//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Detalle_Merma
    {
        public int Id_merma_detalle { get; set; }
        public decimal Costo_unitario { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> Id_Merma { get; set; }
        public Nullable<int> Id_producto { get; set; }
    
        public virtual TBL_Merma TBL_Merma { get; set; }
        public virtual TBL_Productos TBL_Productos { get; set; }
    }
}
