//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CierreCajas
    {
        public int Id_CierreCajas { get; set; }
        public System.DateTime Fecha_Cierre { get; set; }
        public string Tipo_Factura { get; set; }
        public string Forma_Pago { get; set; }
        public decimal Entradas { get; set; }
        public decimal Salidas { get; set; }
        public Nullable<int> Id_factura { get; set; }
    
        public virtual TBL_Factura TBL_Factura { get; set; }
    }
}
