//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Distritos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Distritos()
        {
            this.TBL_Direcciones_cliente = new HashSet<TBL_Direcciones_cliente>();
        }
    
        public string Id_distrito { get; set; }
        public string Id_canton { get; set; }
        public string Id_provincia { get; set; }
        public string Desc_distrito { get; set; }
    
        public virtual TBL_Cantones TBL_Cantones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Direcciones_cliente> TBL_Direcciones_cliente { get; set; }
        public virtual TBL_Provincias TBL_Provincias { get; set; }
    }
}
