//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_Venta_BeerLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Detalle_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Detalle_Factura()
        {
            this.TBL_Productos = new HashSet<TBL_Productos>();
        }
    
        public int Id_detalle_factura { get; set; }
        public string Descripcion_Producto { get; set; }
        public string Codigo { get; set; }
        public decimal Precio_unitario { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> Id_estado { get; set; }
        public Nullable<int> Id_factura { get; set; }
    
        public virtual TBL_Estado TBL_Estado { get; set; }
        public virtual TBL_Factura TBL_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Productos> TBL_Productos { get; set; }
    }
}
